import type { Meta, StoryObj } from "@storybook/react";

import { createRemixStub } from "@remix-run/testing";
import { Temporal } from "temporal-polyfill";
import type { TimeTable } from "content-collections";
import { OverviewSection } from "./OverviewSection";

type T = typeof OverviewSection;

const meta: Meta = {
	component: OverviewSection,
	decorators: [
		(story) => {
			const remixStub = createRemixStub([
				{
					action: () => ({ redirect: "/" }),
					Component: () => story(),
					loader: () => ({ redirect: "/" }),
					path: "/*",
				},
			]);

			return remixStub({ initialEntries: ["/"] });
		},
	],
	parameters: {
		layout: "fullscreen",
	},
	tags: ["autodocs"],
	title: "OverviewSection",
} satisfies Meta<T>;

type Story = StoryObj<T>;

export const Default: Story = {
	args: {
		day1: {
			game: [
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "splatoon.md",
						filePath: "day1/splatoon.md",
						path: "day1/splatoon",
					},
					content: "スプラトゥーン3",
					day: 1,
					endAt: "2024-11-02T14:30:00[Asia/Tokyo]",
					startAt: "2024-11-02T10:45:00[Asia/Tokyo]",
					type: "game",
				},
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "uketsuke.md",
						filePath: "day1/uketsuke.md",
						path: "day1/uketsuke",
					},
					content: "受付",
					day: 1,
					endAt: "2024-11-02T10:45:00[Asia/Tokyo]",
					startAt: "2024-11-02T09:45:00[Asia/Tokyo]",
					type: "game",
				},
			].sort((a, b) => Temporal.ZonedDateTime.compare(Temporal.ZonedDateTime.from(a.startAt), Temporal.ZonedDateTime.from(b.startAt))) as TimeTable[],
			live: [
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "eitisanjuu.md",
						filePath: "day1/eitisanjuu.md",
						path: "day1/eitisanjuu",
					},
					content: "エイチサンジュウ",
					day: 1,
					endAt: "2024-11-02T13:20:00[Asia/Tokyo]",
					startAt: "2024-11-02T12:50:00[Asia/Tokyo]",
					type: "live",
				},
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "lovemayo.md",
						filePath: "day1/lovemayo.md",
						path: "day1/lovemayo",
					},
					content: "羅武❤︎永遠深夜",
					day: 1,
					endAt: "2024-11-02T11:05:00[Asia/Tokyo]",
					startAt: "2024-11-02T10:35:00[Asia/Tokyo]",
					type: "live",
				},
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "nekutai_no_musubikata.md",
						filePath: "day1/nekutai_no_musubikata.md",
						path: "day1/nekutai_no_musubikata",
					},
					content: "ネクタイの結び方",
					day: 1,
					endAt: "2024-11-02T12:35:00[Asia/Tokyo]",
					startAt: "2024-11-02T12:05:00[Asia/Tokyo]",
					type: "live",
				},
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "r04_not_found.md",
						filePath: "day1/r04_not_found.md",
						path: "day1/r04_not_found",
					},
					content: "r04 Not Found",
					day: 1,
					endAt: "2024-11-02T11:50:00[Asia/Tokyo]",
					startAt: "2024-11-02T11:20:00[Asia/Tokyo]",
					type: "live",
				},
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "super_junoesque_band.md",
						filePath: "day1/super_junoesque_band.md",
						path: "day1/super_junoesque_band",
					},
					content: "Super Junoesque Band",
					day: 1,
					endAt: "2024-11-02T14:05:00[Asia/Tokyo]",
					startAt: "2024-11-02T13:35:00[Asia/Tokyo]",
					type: "live",
				},
			].sort((a, b) => Temporal.ZonedDateTime.compare(Temporal.ZonedDateTime.from(a.startAt), Temporal.ZonedDateTime.from(b.startAt))) as TimeTable[],
			main: [
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "concert.md",
						filePath: "day1/concert.md",
						path: "day1/concert",
					},
					content: "音楽部コンサート",
					day: 1,
					endAt: "2024-11-02T10:15:00[Asia/Tokyo]",
					startAt: "2024-11-02T09:45:00[Asia/Tokyo]",
					type: "main",
				},
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "dance1.md",
						filePath: "day1/dance1.md",
						path: "day1/dance1",
					},
					content: "ダンスバトル①",
					day: 1,
					endAt: "2024-11-02T10:35:00[Asia/Tokyo]",
					startAt: "2024-11-02T10:15:00[Asia/Tokyo]",
					type: "main",
				},
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "dance2.md",
						filePath: "day1/dance2.md",
						path: "day1/dance2",
					},
					content: "ダンスバトル②",
					day: 1,
					endAt: "2024-11-02T11:40:00[Asia/Tokyo]",
					startAt: "2024-11-02T11:20:00[Asia/Tokyo]",
					type: "main",
				},
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "dance3.md",
						filePath: "day1/dance3.md",
						path: "day1/dance3",
					},
					content: "ダンスバトル③",
					day: 1,
					endAt: "2024-11-02T12:45:00[Asia/Tokyo]",
					startAt: "2024-11-02T12:25:00[Asia/Tokyo]",
					type: "main",
				},
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "jankenn.md",
						filePath: "day1/jankenn.md",
						path: "day1/jankenn",
					},
					content: "ジャンボたたいてかぶってじゃんけん",
					day: 1,
					endAt: "2024-11-02T12:10:00[Asia/Tokyo]",
					startAt: "2024-11-02T11:40:00[Asia/Tokyo]",
					type: "main",
				},
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "katsuyama.md",
						filePath: "day1/katsuyama.md",
						path: "day1/katsuyama",
					},
					content: "勝山組よさこいパフォーマンス",
					day: 1,
					endAt: "2024-11-02T11:05:00[Asia/Tokyo]",
					startAt: "2024-11-02T10:50:00[Asia/Tokyo]",
					type: "main",
				},
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "minnhaya.md",
						filePath: "day1/minnhaya.md",
						path: "day1/minnhaya",
					},
					content: "みんはや王",
					day: 1,
					endAt: "2024-11-02T13:25:00[Asia/Tokyo]",
					startAt: "2024-11-02T12:45:00[Asia/Tokyo]",
					type: "main",
				},
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "opening.md",
						filePath: "day1/opening.md",
						path: "day1/opening",
					},
					content: "オープニング",
					day: 1,
					endAt: "2024-11-02T09:45:00[Asia/Tokyo]",
					startAt: "2024-11-02T09:00:00[Asia/Tokyo]",
					type: "main",
				},
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "vocal1.md",
						filePath: "day1/vocal1.md",
						path: "day1/vocal1",
					},
					content: "VOCAL1 GP",
					day: 1,
					endAt: "2024-11-02T14:45:00[Asia/Tokyo]",
					startAt: "2024-11-02T13:45:00[Asia/Tokyo]",
					type: "main",
				},
			].sort((a, b) => Temporal.ZonedDateTime.compare(Temporal.ZonedDateTime.from(a.startAt), Temporal.ZonedDateTime.from(b.startAt))) as TimeTable[],
			sub: [
				{
					_meta: {
						directory: ".",
						extension: "md",
						fileName: "alus_tale.md",
						filePath: "alus_tale.md",
						path: "alus_tale",
					},
					content: "Alus Tale",
					day: 1,
					endAt: "2024-11-02T11:45:00[Asia/Tokyo]",
					startAt: "2024-11-02T11:30:00[Asia/Tokyo]",
					type: "sub",
				},
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "acoustic_guiter.md",
						filePath: "day1/acoustic_guiter.md",
						path: "day1/acoustic_guiter",
					},
					content: "アコギ部",
					day: 1,
					endAt: "2024-11-02T14:40:00[Asia/Tokyo]",
					startAt: "2024-11-02T13:30:00[Asia/Tokyo]",
					type: "sub",
				},
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "em.md",
						filePath: "day1/em.md",
						path: "day1/em",
					},
					content: "e/m",
					day: 1,
					endAt: "2024-11-02T12:45:00[Asia/Tokyo]",
					startAt: "2024-11-02T12:30:00[Asia/Tokyo]",
					type: "sub",
				},
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "mikasa.md",
						filePath: "day1/mikasa.md",
						path: "day1/mikasa",
					},
					content: "MIKASA",
					day: 1,
					endAt: "2024-11-02T12:15:00[Asia/Tokyo]",
					startAt: "2024-11-02T12:00:00[Asia/Tokyo]",
					type: "sub",
				},
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "nico.md",
						filePath: "day1/nico.md",
						path: "day1/nico",
					},
					content: "NiCo",
					day: 1,
					endAt: "2024-11-02T13:15:00[Asia/Tokyo]",
					startAt: "2024-11-02T13:00:00[Asia/Tokyo]",
					type: "sub",
				},
				{
					_meta: {
						directory: "day1",
						extension: "md",
						fileName: "rarugo13.md",
						filePath: "day1/rarugo13.md",
						path: "day1/rarugo13",
					},
					content: "ラルゴ13",
					day: 1,
					endAt: "2024-11-02T11:15:00[Asia/Tokyo]",
					startAt: "2024-11-02T11:00:00[Asia/Tokyo]",
					type: "sub",
				},
			].sort((a, b) => Temporal.ZonedDateTime.compare(Temporal.ZonedDateTime.from(a.startAt), Temporal.ZonedDateTime.from(b.startAt))) as TimeTable[],
		},
		day2: {
			game: [
				{
					_meta: {
						directory: "day2",
						extension: "md",
						fileName: "ssbu.md",
						filePath: "day2/ssbu.md",
						path: "day2/ssbu",
					},
					content: "大乱闘スマッシュブラザーズ SPECIAL",
					day: 2,
					endAt: "2024-11-03T12:40:00[Asia/Tokyo]",
					startAt: "2024-11-03T10:30:00[Asia/Tokyo]",
					type: "game",
				},
				{
					_meta: {
						directory: "day2",
						extension: "md",
						fileName: "uketsuke.md",
						filePath: "day2/uketsuke.md",
						path: "day2/uketsuke",
					},
					content: "受付",
					day: 2,
					endAt: "2024-11-03T10:30:00[Asia/Tokyo]",
					startAt: "2024-11-03T09:30:00[Asia/Tokyo]",
					type: "game",
				},
			].sort((a, b) => Temporal.ZonedDateTime.compare(Temporal.ZonedDateTime.from(a.startAt), Temporal.ZonedDateTime.from(b.startAt))) as TimeTable[],
			live: [
				{
					_meta: {
						directory: "day2",
						extension: "md",
						fileName: "curious.md",
						filePath: "day2/curious.md",
						path: "day2/curious",
					},
					content: "Curious",
					day: 2,
					endAt: "2024-11-03T11:20:00[Asia/Tokyo]",
					startAt: "2024-11-03T10:50:00[Asia/Tokyo]",
					type: "live",
				},
				{
					_meta: {
						directory: "day2",
						extension: "md",
						fileName: "keen.md",
						filePath: "day2/keen.md",
						path: "day2/keen",
					},
					content: "κεεη",
					day: 2,
					endAt: "2024-11-03T10:40:00[Asia/Tokyo]",
					startAt: "2024-11-03T10:10:00[Asia/Tokyo]",
					type: "live",
				},
				{
					_meta: {
						directory: "day2",
						extension: "md",
						fileName: "nobody_s.md",
						filePath: "day2/nobody_s.md",
						path: "day2/nobody_s",
					},
					content: "nobody's",
					day: 2,
					endAt: "2024-11-03T11:55:00[Asia/Tokyo]",
					startAt: "2024-11-03T11:35:00[Asia/Tokyo]",
					type: "live",
				},
				{
					_meta: {
						directory: "day2",
						extension: "md",
						fileName: "ramb_ling.md",
						filePath: "day2/ramb_ling.md",
						path: "day2/ramb_ling",
					},
					content: "Ramb'Ling",
					day: 2,
					endAt: "2024-11-03T10:00:00[Asia/Tokyo]",
					startAt: "2024-11-03T09:30:00[Asia/Tokyo]",
					type: "live",
				},
			].sort((a, b) => Temporal.ZonedDateTime.compare(Temporal.ZonedDateTime.from(a.startAt), Temporal.ZonedDateTime.from(b.startAt))) as TimeTable[],
			main: [
				{
					_meta: {
						directory: "day2",
						extension: "md",
						fileName: "concert.md",
						filePath: "day2/concert.md",
						path: "day2/concert",
					},
					content: "音楽部コンサート",
					day: 2,
					endAt: "2024-11-03T09:30:00[Asia/Tokyo]",
					startAt: "2024-11-03T09:00:00[Asia/Tokyo]",
					type: "main",
				},
				{
					_meta: {
						directory: "day2",
						extension: "md",
						fileName: "final_live.md",
						filePath: "day2/final_live.md",
						path: "day2/final_live",
					},
					content: "決勝ライブ",
					day: 2,
					endAt: "2024-11-03T13:25:00[Asia/Tokyo]",
					startAt: "2024-11-03T12:25:00[Asia/Tokyo]",
					type: "main",
				},
				{
					_meta: {
						directory: "day2",
						extension: "md",
						fileName: "finale.md",
						filePath: "day2/finale.md",
						path: "day2/finale",
					},
					content: "フィナーレ",
					day: 2,
					endAt: "2024-11-03T15:55:00[Asia/Tokyo]",
					startAt: "2024-11-03T15:25:00[Asia/Tokyo]",
					type: "main",
				},
				{
					_meta: {
						directory: "day2",
						extension: "md",
						fileName: "kayousai.md",
						filePath: "day2/kayousai.md",
						path: "day2/kayousai",
					},
					content: "スズカ高専歌謡祭",
					day: 2,
					endAt: "2024-11-03T11:10:00[Asia/Tokyo]",
					startAt: "2024-11-03T10:30:00[Asia/Tokyo]",
					type: "main",
				},
				{
					_meta: {
						directory: "day2",
						extension: "md",
						fileName: "marubatsu.md",
						filePath: "day2/marubatsu.md",
						path: "day2/marubatsu",
					},
					content: "マルバツ",
					day: 2,
					endAt: "2024-11-03T11:55:00[Asia/Tokyo]",
					startAt: "2024-11-03T11:25:00[Asia/Tokyo]",
					type: "main",
				},
				{
					_meta: {
						directory: "day2",
						extension: "md",
						fileName: "memories.md",
						filePath: "day2/memories.md",
						path: "day2/memories",
					},
					content: "メモリーズ",
					day: 2,
					endAt: "2024-11-03T15:25:00[Asia/Tokyo]",
					startAt: "2024-11-03T13:40:00[Asia/Tokyo]",
					type: "main",
				},
			].sort((a, b) => Temporal.ZonedDateTime.compare(Temporal.ZonedDateTime.from(a.startAt), Temporal.ZonedDateTime.from(b.startAt))) as TimeTable[],
			sub: [
				{
					_meta: {
						directory: "day2",
						extension: "md",
						fileName: "acoustic_guiter.md",
						filePath: "day2/acoustic_guiter.md",
						path: "day2/acoustic_guiter",
					},
					content: "アコギ部",
					day: 2,
					endAt: "2024-11-03T13:30:00[Asia/Tokyo]",
					startAt: "2024-11-03T09:30:00[Asia/Tokyo]",
					type: "sub",
				},
			].sort((a, b) => Temporal.ZonedDateTime.compare(Temporal.ZonedDateTime.from(a.startAt), Temporal.ZonedDateTime.from(b.startAt))) as TimeTable[],
		},
	},
};

export default meta;
