name: Deploy to staging

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  deployments: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.page.outputs.deployment-url }}
    steps:
      - name: Setup | Comment deploy start
        uses: mshick/add-pr-comment@v2.8.2
        with:
          message-id: dev-deploy
          message: |
            ### <span aria-hidden="true">🚧</span> Deploy Preview building...

            |  Name | Link |
            |---------------------------------|------------------------|
            |<span aria-hidden="true">🔨</span> Latest commit | ${{ github.sha }} |
            |<span aria-hidden="true">🔍</span> Latest deploy log | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            ---
      - uses: actions/checkout@v4.2.1
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.6.0
        with:
          node-version-file: .nvmrc
      - name: Deploy | Build
        run: pnpm build
      - name: Deploy | Deploy to Cloudflare Pages
        id: page
        uses: cloudflare/wrangler-action@v3.8.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy --project-name 2024-hp --directory build/client
      - name: PostDeploy | Comment deploy url
        uses: mshick/add-pr-comment@v2.8.2
        with:
          message-id: cloudflare-deploy
          message: |
            ### <span aria-hidden="true">✅</span> Deploy Preview ready!

            |  Name | Link |
            |---------------------------------|------------------------|
            |<span aria-hidden="true">🔨</span> Latest commit | ${{ github.sha }} |
            |<span aria-hidden="true">🔍</span> Latest deploy log | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            |<span aria-hidden="true">😎</span> Deploy Preview Url | [${{ steps.page.outputs.deployment-url }}](${{ steps.page.outputs.deployment-url }}) |
            ---
  lighthouse:
    needs: publish
    uses: ./.github/workflows/lighthouse.yml
    with:
      url: ${{ needs.publish.outputs.url }}
  storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Comment deploy start
        uses: mshick/add-pr-comment@v2.8.2
        with:
          message-id: sb-deploy
          message: |
            ### <span aria-hidden="true">🚧</span> Deploy Preview building...

            |  Name | Link |
            |---------------------------------|------------------------|
            |<span aria-hidden="true">🔨</span> Latest commit | ${{ github.sha }} |
            |<span aria-hidden="true">🔍</span> Latest deploy log | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            ---
      - uses: actions/checkout@v4.2.1
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.6.0
        with:
          node-version-file: .nvmrc
      - name: Deploy | Build Storybook
        run: pnpm build-storybook
      - name: Deploy | Build
        run: pnpm build
      - name: Deploy | Deploy to Cloudflare Pages
        id: page
        uses: cloudflare/wrangler-action@v3.8.0
        with:
          apiToken: ${{ secrets.CF_SB_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy --project-name 2024-hp-sb --directory storybook-static
      - name: PostDeploy | Comment deploy url
        uses: mshick/add-pr-comment@v2.8.2
        with:
          message-id: cloudflare-sb-deploy
          message: |
            ### <span aria-hidden="true">✅</span> Deploy Storybook Preview ready!

            |  Name | Link |
            |---------------------------------|------------------------|
            |<span aria-hidden="true">🔨</span> Latest commit | ${{ github.sha }} |
            |<span aria-hidden="true">🔍</span> Latest deploy log | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            |<span aria-hidden="true">😎</span> Deploy Preview Url | [${{ steps.page.outputs.deployment-url }}](${{ steps.page.outputs.deployment-url }}) |
            ---
