name: Lighthouse Report

on:
  workflow_call:
    inputs:
      url:
        description: URL to audit
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lighthouse-report:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.5.4
        with:
          node-version-file: .nvmrc
      - name: Run | Audit URLs using Lighthouse
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@11.4.0
        with:
          urls: |
            ${{ inputs.url }}
          configPath: ./.github/lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true
      - name: Run | Format lighthouse score
        id: format_lighthouse_score
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const results = ${{ steps.lighthouse_audit.outputs.manifest }};
            const links = ${{ steps.lighthouse_audit.outputs.links }};
            const createLighthouseReport = (await import(`${process.env.GITHUB_WORKSPACE}/.github/scripts/formatLighthouseReport.js`)).default;
            const comment = createLighthouseReport({ results, links });
            core.setOutput("comment", comment);
      - name: Post | Add Lighthouse stats as comment
        id: comment_to_pr
        uses: marocchino/sticky-pull-request-comment@v2.9.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          header: lighthouse
          message: ${{ steps.format_lighthouse_score.outputs.comment }}
