name: Release

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4.1.5
        with:
          ref: main
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.5.4
        with:
          node-version-file: .nvmrc
      - name: Deploy | Build
        run: pnpm build
      - name: Deploy | Deploy to Cloudflare Pages
        id: page
        uses: cloudflare/wrangler-action@v3.5.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy --project-name 2024-hp --directory build/client
